export { Orizn, MAX_BULK_DESTINATIONS } from "./client.js";
export { LANGUAGES, normalizeRequirement, isUpgradeNotice } from "./types.js";
export type {
  CanonicalRequirement,
  VisaRequirement,
  Language,
  Gated,
  UpgradeNotice,
  Extensible,
  VisaData,
  VisaCheckResult,
  VisaResponse,
  BulkDestination,
  BulkResponse,
  CoverageStats,
  CountryInfo,
  OriznConfig,
  PartnerLink,
  TransitHub,
  TransitVisa,
  Money,
  VisaFee,
  VisaType,
  ProcessingDays,
  PhotoSpecs,
  InsuranceRequired,
  MinorRules,
  OverstayPenalty,
  EntryByMode,
  RemoteWorkVisa,
  ExtensionRules,
  ReciprocityChange,
  ReciprocityHistory,
  SafetyInfo,
  HealthRequirements,
  EmbassyInfo,
  EmbassyList,
  EmbassyData,
} from "./types.js";
export {
  OriznError,
  OriznAuthError,
  OriznInvalidKeyError,
  OriznPlanError,
  OriznRateLimitError,
  OriznNotFoundError,
  OriznBadRequestError,
  SIGNUP_URL,
  DASHBOARD_URL,
  UPGRADE_URL,
} from "./errors.js";
